- name: Playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Apply all manifests
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ item }}') }}"
        namespace: default
        kubeconfig: "/usr"
      with_fileglob:
        - "deployment.yml"
        - "service.yml"