apiVersion: v1
kind: Service              
metadata:
  name: udacity-s
spec:
  type: LoadBalancer  
  ports:
  - port: 8080        
    protocol: TCP     
    targetPort: 80 
  selector:        
    app: udacity